Add syllabus meeting minutes for 02-03-2022
CodeYourFuture/syllabus pull request #388
Opened 2022-03-02 19:48 UTC by Dedekind561

## Description

Adds notes for syllabus meeting 02-03-2022

## Who needs to know about this?

@CodeYourFuture/syllabus-team 

## Rendered Pages

2022-03-02 19:50 UTC, Dedekind561 commented on docs/contributing/minutes.md
> +- Some node module changes proposals ( Barath / Sanyia ) - Use of wordle in Lesson 3 of the Node module
@sansaid Please could you add a link to your node module proposals - I think I saw a google doc in the meeting

2022-03-02 19:50 UTC, Dedekind561 commented on docs/contributing/minutes.md
> +- Further delegation to module teams
@gregdyke Think you went through a list of post-its but I may have missed off one or 2 if you want add them in here

2022-03-03 16:00 UTC, SallyMcGrath requested changes

2022-03-03 16:00 UTC, SallyMcGrath commented on docs/contributing/minutes.md
> +- Further delegation to module teams
```suggestion
- Further empowerment of module teams
```

2022-03-03 16:00 UTC, SallyMcGrath commented on docs/contributing/minutes.md
> +- Cross module stuff
```suggestion
- Cross module threads: code review, TDD, problem solving
```

2022-03-03 16:00 UTC, SallyMcGrath commented on docs/contributing/minutes.md
> +- Someone could join JS2 to suppor them with getting through some tasks
```suggestion
- Someone could join JS2 to support them with getting through some tasks
```

2022-03-03 16:00 UTC, SallyMcGrath commented on docs/contributing/minutes.md
> +- We welcome to Sanyia to the Syllabus Team
```suggestion
- We welcome Sanyia to the Syllabus Team
```

2022-03-03 16:00 UTC, SallyMcGrath commented on docs/contributing/minutes.md
> +- Greg to lead with support from Mitch
```suggestion
- Greg to lead with support from Mitch 12 March
```

2022-03-03 16:00 UTC, SallyMcGrath commented on docs/contributing/minutes.md
> +- Mention pedagogic techniques in remot environment: no slides, cold calling, screen sharing, live code demos etc ...
```suggestion
- Mention pedagogic techniques in remote environment: no slides, cold calling, screen sharing, live code demos etc ...
```

2022-03-07 12:35 UTC, merged

2022-03-17 09:15 UTC, SallyMcGrath commented
@all-contributors please add @Dedekind561 for review, tests and code