Updating Sally's suggestions + link
CodeYourFuture/syllabus pull request #538
Opened 2022-11-28 14:42 UTC by kfklein15

Signed-off-by: KFK <80272258+kfklein15@users.noreply.github.com>

## What does this change?

Module: Final Projects
Week(s): preparation

## Description

 Changed Sally's suggestion's as well as amended links to team file (which wasn't working anymore) and to the Roles (which have been moved to Gitbook)

## Who needs to know about this?

 @MarianaVazquezCYF @martaesn @ShaunCYFSA @AliciaE08 @caromelendezl 

## Rendered Pages

2022-12-02 22:58 UTC, SallyMcGrath requested changes
A few tweaks. Mainly around links, and then more SPAG.

2022-12-02 22:58 UTC, SallyMcGrath commented on docs/finalproject/prep.md
> +- [ ] If you haven't yet, make sure you dentify trainees that will be filling in roles such as UI/UX Designer, Tester or Product Delivery
```suggestion
- [ ] If you haven't yet, make sure you identify trainees that will be filling in roles such as UI/UX Designer, Tester or Product Delivery
```

2022-12-02 22:58 UTC, SallyMcGrath commented on docs/finalproject/prep.md
> +- [ ] Trainees' must have completed up to Level 300 of the Full Stack assessment by week 3 of the module before Final Projects and finalised
```suggestion
- [ ] Trainees must have completed up to Level 300 of the [Full Stack Assessment](https://github.com/CodeYourFuture/Table-of-Contents) by week 3 of the module before Final Projects.
```

This is plural, but not plural possessive, in this case. It was the other use of trainees in your previous PR that was plural possessive. It's a minefield! 😅

2022-12-02 22:58 UTC, SallyMcGrath commented on docs/finalproject/prep.md
>  - [ ] Ask internally and externally for possible ideas of charities that could be part of Final Projects. The form used should be [this](https://forms.gle/Gn85Kdna6QB2Qfcp9).
```suggestion
- [ ] Ask internally and externally for possible ideas of charities that could be part of Final Projects. The form used should be the [Final Project Proposals form](https://forms.gle/Gn85Kdna6QB2Qfcp9). 
```

Links must make sense out of context. https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html

2022-12-02 22:58 UTC, SallyMcGrath commented on docs/finalproject/prep.md
>  - [ ] Start recruiting Tech Lead, Product Managers and UI/UX Designer for Final Projects. See the role descriptions [here](https://docs.codeyourfuture.io/volunteers/teams-1/cyf-products-final-project
```suggestion
- [ ] Start recruiting Tech Lead, Product Managers and UI/UX Designer for Final Projects. See the [role descriptions](https://docs.codeyourfuture.io/volunteers/teams-1/cyf-products-final-projects/roles). 
```

Links must make sense out of context. https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html

2022-12-02 22:58 UTC, SallyMcGrath commented on docs/finalproject/prep.md
> +You can find a template for organising the teams[here](https://docs.google.com/spreadsheets/d/16vSSJgzCZJKF-2pwuBTkKjJJJ9i1CGRqMbYB-HEO5mo/edit?usp=sharing).
```suggestion
Please make a copy of this [template spreadsheet](https://docs.google.com/spreadsheets/d/16vSSJgzCZJKF-2pwuBTkKjJJJ9i1CGRqMbYB-HEO5mo/edit?usp=sharing) to organise the teams and track the progress of the projects.
```

Links must make sense out of context. This is important for accessibility. https://www.w3.org/QA/Tips/noClickHere

2022-12-02 22:58 UTC, SallyMcGrath commented on docs/finalproject/prep.md
> +All trainees should make sure that they are comfortable with their roles and what they will be required to do. More information about roles can be found [here](https://docs.codeyourfuture.io/voluntee
```suggestion
All trainees should make sure that they are comfortable with their roles and what they will be required to do. More [information about roles](https://docs.codeyourfuture.io/volunteers/teams-1/cyf-products-final-projects/roles).
```

https://www.gov.uk/guidance/content-design/links

2022-12-02 22:58 UTC, SallyMcGrath commented on docs/finalproject/prep.md
> +- [ ] Have a meeting with all volunteers and trainees to go through the details of the final project (presentation to be created with expectation, escalation process, type of support, overview of the
```suggestion
- [ ] Have a meeting with all volunteers and trainees to go through the details of the final project (presentation to be created with expectation, escalation process, type of support, overview of the trainees per team, etc). Don't forget to record it and share the recording with all the participants, with their consent.
```

2022-12-05 11:31 UTC, kfklein15 commented
All committed, @SallyMcGrath . Thanks

2022-12-05 12:53 UTC, SallyMcGrath approved these changes, later dismissed
LGTM 🌮

2022-12-05 12:53 UTC, SallyMcGrath commented on docs/finalproject/prep.md
>  - [ ] Must review the trainee’s performance and identify the ones going to Final Projects
```suggestion
- [ ] Must review the trainees' performance and identify the ones going to Final Projects
```

2022-12-05 12:54 UTC, SallyMcGrath approved these changes
and again

2022-12-05 13:35 UTC, merged