Updating stand-up and github projects
CodeYourFuture/syllabus pull request #543
Opened 2022-12-01 11:09 UTC by kfklein15

Signed-off-by: KFK <80272258+kfklein15@users.noreply.github.com>

## What does this change?

Module: Final Projects
Week(s): Week 1 - Lesson

## Description

 Added the information about Github projects and that they should read each others stand-up

## Who needs to know about this?

 @MarianaVazquezCYF @martaesn @AliciaE08 @ShaunCYFSA 

## Rendered Pages

2022-12-02 22:06 UTC, SallyMcGrath requested changes
Minor changes

2022-12-02 22:06 UTC, SallyMcGrath commented on docs/finalproject/week-1/lesson.md
> +Don't forget to also read your team mates updates. This way you can understand what is happening in the team and support anyone that needs it.
```suggestion
Don't forget to also read your teammates updates. This way you can understand what is happening in the team and support each other.
```

https://www.macmillandictionary.com/dictionary/british/teammate

2022-12-02 22:06 UTC, SallyMcGrath commented on docs/finalproject/week-1/lesson.md
>  Set a time for this and stick to it.
```suggestion
Set a time for this and stick to it. Put it in your calendar.
```

2022-12-05 11:19 UTC, kfklein15 commented
All accepted, @SallyMcGrath , Just need your final approval. Thank you

2022-12-05 13:30 UTC, SallyMcGrath approved these changes
LGTM 🎉

2022-12-05 13:42 UTC, merged