Added explanation and extra info to title
CodeYourFuture/syllabus pull request #544
Opened 2022-12-01 11:13 UTC by kfklein15

Signed-off-by: KFK <80272258+kfklein15@users.noreply.github.com>

## What does this change?

Module: Final Projects
Week(s): Week 3

## Description

 Added more information to make sure people understand we are repeating everything weekly. I also added info to the Check In title to make sure people look at it and understand the importance of it.

## Who needs to know about this?

 @MarianaVazquezCYF @martaesn @AliciaE08 @ShaunCYFSA 

## Rendered Pages

2022-12-02 22:12 UTC, SallyMcGrath requested changes
Minor changes, but please do use Grammarly to check SPAG before submission. Thanks!

2022-12-02 22:12 UTC, SallyMcGrath commented on docs/finalproject/week-3/lesson.md
> +### Check In: how is the contribuitions of all team members so far?
```suggestion
### Check In: how are the contributions of all team members so far?
```

Minor changes

Subject verb agreement https://www.grammarbook.com/grammar/subjectVerbAgree.asp
Spelling

2022-12-05 11:22 UTC, kfklein15 commented
@SallyMcGrath all accepted and committed.

2022-12-05 13:32 UTC, SallyMcGrath approved these changes
LGTM 🌮

2022-12-05 13:42 UTC, merged