Added some meat and remineder
CodeYourFuture/syllabus pull request #545
Opened 2022-12-01 11:16 UTC by kfklein15

Signed-off-by: KFK <80272258+kfklein15@users.noreply.github.com>

## What does this change?

Module: Final Projects
Week(s): Week 4

## Description

Added some extra explanation and a reminder about the contributions.

## Who needs to know about this?

## Rendered Pages

2022-12-02 22:08 UTC, SallyMcGrath requested changes
Minor changes

2022-12-02 22:08 UTC, SallyMcGrath commented on docs/finalproject/week-4/lesson.md
> +See [Week 2](../week-2/lesson) for instructions for this week. And make sure to check in again on the contribuitions per team members, as detailed on Week 3 [Week 3](../week-3/lesson)
```suggestion
See [Week 2](../week-2/lesson) for instructions for this week. 

Make sure to check in again on the contributions per team members, as detailed on Week 3 [Week 3](../week-3/lesson)
```

Please use spellcheck for submissions to the Syllabus. 🙏

2022-12-05 11:21 UTC, kfklein15 commented
@SallyMcGrath , another one for your final approval.

2022-12-05 13:29 UTC, SallyMcGrath requested changes
Minor changes

2022-12-05 13:29 UTC, SallyMcGrath commented on docs/finalproject/week-4/lesson.md
> +Make sure to check in again on the contributions per team members, as detailed on Week 3 [Week 3](../week-3/lesson)
```suggestion
Make sure to check in again on the contributions per team members, as detailed on [Week 3](../week-3/lesson)
```

2022-12-05 13:29 UTC, SallyMcGrath commented on docs/finalproject/week-4/lesson.md
> +Make sure to check in again on the contributions per team members, as detailed on Week 3 [Week 3](../week-3/lesson)
repeated phrase here

2022-12-05 14:24 UTC, SallyMcGrath approved these changes
LGTM

2022-12-05 14:40 UTC, merged