Professional Development Content
CodeYourFuture/syllabus pull request #551
Opened 2022-12-12 15:50 UTC by ElizabethlawalCYF

User stories and sprints

Added PD content on on agile methodology. 

Do you know how to add slides? I have pasted the link directly into the repo but I think there is a much smarter way of doing this.. 

Signed-off-by: ElizabethlawalCYF <101108952+ElizabethlawalCYF@users.noreply.github.com>

## What does this change?

Module:
Week(s):

## Description

## Who needs to know about this?

## Rendered Pages

2023-01-09 20:49 UTC, SallyMcGrath requested changes
Some minor notes and tweaks

2023-01-09 20:49 UTC, SallyMcGrath commented on docs/react/week-1/lesson.md
> +**Session: User stories and sprints**
```suggestion
### Session: User stories and sprints
```

2023-01-09 20:49 UTC, SallyMcGrath commented on docs/react/week-1/lesson.md
> +**
```suggestion
#### Client Brief
```

2023-01-09 20:49 UTC, SallyMcGrath commented on docs/react/week-1/lesson.md
> +Task**
```suggestion

```

2023-01-09 20:49 UTC, SallyMcGrath commented on docs/react/week-1/lesson.md
> +Client Brief:
```suggestion
```

2023-01-09 20:49 UTC, SallyMcGrath commented on docs/react/week-1/lesson.md
> +A small hotel owner, after many years in business, has decided to go to the next level, perform renovations and then go online. An important part of this journey will be to build an online hotel book
```suggestion
A small hotel owner, after many years in business, has decided to perform renovations and then go online. An important part of this journey will be to build an online hotel booking app.
```

2023-01-09 20:49 UTC, SallyMcGrath commented on docs/react/week-1/lesson.md
> +The hotel owner would like to have a welcome page where people can find all the information they need about the hotel and from there, app users can go to the booking section.
```suggestion
The hotel owner would like to have a welcome page where users can find all the information they need about the hotel. From there, users can go to the booking section.
```

2023-01-09 20:49 UTC, SallyMcGrath commented on docs/react/week-1/lesson.md
> +Exercise (20 min)
```suggestion
:::note Exercise (20 min)
```

This is how we demark an exercise block, :::note

2023-01-09 20:49 UTC, SallyMcGrath commented on docs/react/week-1/lesson.md
> +Resources required: Use Gitprojects to plan your project.
```suggestion
Resources required: Use [GitHub Projects](https://github.com/features/issues) to plan your project. 
```

2023-01-09 20:49 UTC, SallyMcGrath commented on docs/react/week-1/lesson.md
> +In small groups. Plan the app project and create user stories/scenarios.
```suggestion
In small groups. Plan the app project and create user stories/scenarios on a Jam Board or sticky notes. Look at Fundamentals again to remind you.
```

2023-01-09 20:49 UTC, SallyMcGrath commented on docs/react/week-1/lesson.md
> +Exercise (40 min)
```suggestion
:::note Exercise (40 min)
```

2023-01-09 20:49 UTC, SallyMcGrath commented on docs/react/week-1/lesson.md
> +
```suggestion
::: 
```

2023-01-09 20:49 UTC, SallyMcGrath commented on docs/react/week-1/lesson.md
> +Resources required: Gitprojects.
```suggestion
Resources required: [GitHub Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/quickstart-for-projects).
```

They aren't called Gitprojects!

2023-01-09 20:49 UTC, SallyMcGrath commented on docs/react/week-1/lesson.md
>  :::
```suggestion

```

2023-01-24 09:06 UTC, kfklein15 commented
@ElizabethlawalCYF , hope it is ok to close this PR. Since Esma is reviewing it all and moving it, this could generate a PR conflict ;) (your first one)

2023-01-24 09:06 UTC, closed without merging