PD-JS3-W3
CodeYourFuture/syllabus pull request #617
Opened 2023-02-09 15:08 UTC by esma-g

## What does this change?

Module: JS3
Week(s): 3

## Checklist

- [x] I have read the [contributing guidelines](https://syllabus.codeyourfuture.io/contributing/overview)
- [x] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x] I have run my code to check it works
- [x] My changes follow our [Style Guide](https://syllabus.codeyourfuture.io/guides/code-style-guide)

## Description

Transferred PD content from [the PD website](https://personal-development.codeyourfuture.io/em-modules/javascript-3/week-3-agile-scrum-planning)

## Who needs to know about this?

@kfklein15 @ElizabethlawalCYF @CodeYourFuture/syllabus-team 

Rendered Pages
https://syllabus.codeyourfuture.io/js-core-3/week-3/lesson
https://syllabus.codeyourfuture.io/js-core-3/week-2/homework

2023-02-10 10:22 UTC, kfklein15 requested changes
one tiny change

2023-02-10 10:22 UTC, kfklein15 commented on docs/js-core-3/week-3/lesson.md
> +Step 3: Work together and review all of the tasks you need to do to complete your individual projects (please note that you might be at different stages of completion). Organise your tasks in four ca
Backlog, not Backlogged :)

2023-02-10 14:07 UTC, esma-g commented on docs/js-core-3/week-3/lesson.md
> +Step 3: Work together and review all of the tasks you need to do to complete your individual projects (please note that you might be at different stages of completion). Organise your tasks in four ca
> Backlog, not Backlogged :)

Done

2023-02-10 15:08 UTC, kfklein15 approved these changes
lgtm

2023-02-16 22:55 UTC, illicitonion approved these changes

2023-02-16 22:55 UTC, merged