Pd js2 w1
CodeYourFuture/syllabus pull request #652
Opened 2023-03-16 19:18 UTC by esma-g

## What does this change?

Module: JS2
Week(s): 1

## Checklist

- [x] I have read the [contributing guidelines](https://syllabus.codeyourfuture.io/contributing/overview)
- [x] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x] I have run my code to check it works
- [x] My changes follow our [Style Guide](https://syllabus.codeyourfuture.io/guides/code-style-guide)

## Description

Added PD lesson and coursework. Editing week 2-4 by mistake in this PR, removed them later on.

## Who needs to know about this?

@kfklein15 @CodeYourFuture/syllabus-team 

## Rendered Pages

2023-03-20 16:07 UTC, kfklein15 requested changes
Asked for minor changes

2023-03-20 16:07 UTC, kfklein15 commented on docs/js-core-2/week-1/lesson.md
> +- A UX/UI designer or UX researcher: Provides the design of the website
design and user experience

2023-03-20 16:07 UTC, kfklein15 commented on docs/js-core-2/week-1/lesson.md
> +- Team lead / Manager: Hands-on developer responsible for the wellbeing of the team, and team morale (sometimes has people management responsibilities)
Hmmm not sure this one makes sense. I would stop at Tech Lead

2023-03-20 16:07 UTC, kfklein15 commented on docs/js-core-2/week-1/lesson.md
> +- Team lead / Manager
This one doesn't make sense to me

2023-03-22 00:00 UTC, illicitonion reviewed
Looks great, just a few minor things - thanks!

2023-03-22 00:00 UTC, illicitonion commented on docs/js-core-2/week-1/lesson.md
> +Think about the teams you will work with in future when you move in tech. Discuss in groups:
```suggestion
Think about the teams you will work with in the future when you move into tech. Discuss in groups:
```

2023-03-22 00:00 UTC, illicitonion commented on docs/js-core-2/week-1/lesson.md
> +Match the process to the stage in the software development cycle (SDC) as a class. Don’t go too much into detail, you can do some research later if you would like to learn more. These processes vary
I'm more familiar with the term SDLC - Software Development Lifecycle; is SDC commonly used too?

2023-03-22 00:00 UTC, illicitonion commented on docs/js-core-2/week-1/lesson.md
> +Remember, there will be a more detailed PD session on conflict resolution in the upcoming weeks. Work in groups for about 5 minutes, then discuss as a class for 5 minutes:
```suggestion
**Exercise objective:** To brainstorm about the causes of conflicts and methods to manage them

Remember, there will be a more detailed PD session on conflict resolution in the upcoming weeks. Work in groups for about 5 minutes, then discuss as a class for 5 minutes:
```

If there's not an empty line between two lines in markdown, the two lines get folded into one.

2023-03-22 00:00 UTC, illicitonion commented on docs/js-core-2/week-3/lesson.md
> +  - [PD - Delivery](#pd-delivery)
Accidentally added in this PR?

2023-03-22 00:00 UTC, illicitonion commented on docs/js-core-2/week-4/lesson.md
> +  - [PD - Presentations](#pd-presentations)
Accidentally added in this PR?

2023-03-22 14:21 UTC, esma-g commented on docs/js-core-2/week-1/lesson.md
> +Match the process to the stage in the software development cycle (SDC) as a class. Don’t go too much into detail, you can do some research later if you would like to learn more. These processes vary
The developers in the PD syllabus team suggested SDC. Would you like me to change @illicitonion ?

2023-03-22 14:22 UTC, esma-g commented on docs/js-core-2/week-4/lesson.md
> +  - [PD - Presentations](#pd-presentations)
Yes, sorry. fixed

2023-03-22 14:30 UTC, esma-g commented on docs/js-core-2/week-1/lesson.md
> +- A UX/UI designer or UX researcher: Provides the design of the website
fixed

2023-03-22 14:30 UTC, esma-g commented on docs/js-core-2/week-1/lesson.md
> +- Team lead / Manager: Hands-on developer responsible for the wellbeing of the team, and team morale (sometimes has people management responsibilities)
fixed

2023-03-22 14:30 UTC, esma-g commented on docs/js-core-2/week-1/lesson.md
> +- Team lead / Manager
fixed

2023-03-22 14:31 UTC, esma-g commented on docs/js-core-2/week-3/lesson.md
> +  - [PD - Delivery](#pd-delivery)
Yes, sorry. fixed

2023-03-23 19:40 UTC, illicitonion commented on docs/js-core-2/week-1/lesson.md
> +Match the process to the stage in the software development cycle (SDC) as a class. Don’t go too much into detail, you can do some research later if you would like to learn more. These processes vary
Yeah, I'd go with SDLC if that's ok, sorry!

2023-03-23 19:41 UTC, illicitonion submitted a review, later dismissed

2023-03-23 19:54 UTC, illicitonion commented
I just force-pushed resolving all the conflicts from the other PRs, as well as applying the SDC -> SDLC update - hope you don't mind!

If you wanted to make more edits, you should pull down the changes before you edit more :)

2023-03-23 19:54 UTC, illicitonion approved these changes

2023-04-03 15:51 UTC, esma-g commented
@kfklein15 Could I get a review for this one, please?

2023-04-03 15:52 UTC, kfklein15 approved these changes
lgtm

2023-04-03 15:52 UTC, merged