Added PD DB W1
CodeYourFuture/syllabus pull request #676
Opened 2023-04-23 16:40 UTC by esma-g

## What does this change?

Module: DB
Week(s): 1

## Checklist

- [ ] I have read the [contributing guidelines](https://syllabus.codeyourfuture.io/contributing/overview)
- [ ] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [ ] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [ ] I have run my code to check it works
- [ ] My changes follow our [Style Guide](https://syllabus.codeyourfuture.io/guides/code-style-guide)

## Description

Added PD DB W1

## Who needs to know about this?

@kfklein15 @CodeYourFuture/syllabus-team 

## Rendered Pages

2023-04-24 07:53 UTC, kfklein15 requested changes

2023-04-24 07:53 UTC, kfklein15 commented on docs/db/week-1/homework.md
> +Use [the provided spreadsheet](https://docs.google.com/spreadsheets/d/1JvPFFewdrVP7nY7sL7l13TeGUxLos7h3NxWb0itxm84/edit#gid=0) to come up with interview examples in line with the STAR framework.
```suggestion
Use [the provided spreadsheet](https://docs.google.com/spreadsheets/d/1JvPFFewdrVP7nY7sL7l13TeGUxLos7h3NxWb0itxm84/edit#gid=0) to come up with interview examples in line with the STAR framework.
Don't forget to make a copy of this spreadsheet, before adding your information to it.
```

2023-04-24 07:53 UTC, kfklein15 commented on docs/db/week-1/lesson.md
> +**Exercise objective:** To observe implementation of STAR framework for competency-based interviews
Do we need both exercises? Just asking since it is more effective to analyse than observe.

2023-04-25 12:10 UTC, esma-g commented on docs/db/week-1/lesson.md
> +**Exercise objective:** To observe implementation of STAR framework for competency-based interviews
They are not only observing but also discussing following their observation.

2023-04-25 12:10 UTC, esma-g commented
@illicitonion this PR has conflicting files. I have no idea how to resolve them, can you help please?

2023-05-02 12:26 UTC, closed without merging